import graph_structure as gs


def build_graph(new_graph):

    # Create each node with it's name and heuristic value relative to the center (Node 55).
    new_graph.add_node(gs.Node('1', 100))
    new_graph.add_node(gs.Node('2', 101))
    new_graph.add_node(gs.Node('3', 90))
    new_graph.add_node(gs.Node('4', 81))
    new_graph.add_node(gs.Node('5', 76))
    new_graph.add_node(gs.Node('6', 85))
    new_graph.add_node(gs.Node('7', 85))
    new_graph.add_node(gs.Node('8', 90))
    new_graph.add_node(gs.Node('9', 91))
    new_graph.add_node(gs.Node('10', 100))
    new_graph.add_node(gs.Node('11', 73))
    new_graph.add_node(gs.Node('12', 51))
    new_graph.add_node(gs.Node('13', 32))
    new_graph.add_node(gs.Node('14', 51))
    new_graph.add_node(gs.Node('15', 55))
    new_graph.add_node(gs.Node('16', 80))
    new_graph.add_node(gs.Node('17', 83))
    new_graph.add_node(gs.Node('18', 99))
    new_graph.add_node(gs.Node('19', 98))
    new_graph.add_node(gs.Node('20', 93))
    new_graph.add_node(gs.Node('21', 70))
    new_graph.add_node(gs.Node('22', 67))
    new_graph.add_node(gs.Node('23', 30))
    new_graph.add_node(gs.Node('24', 28))
    new_graph.add_node(gs.Node('25', 66))
    new_graph.add_node(gs.Node('26', 68))
    new_graph.add_node(gs.Node('27', 64))
    new_graph.add_node(gs.Node('28', 69))
    new_graph.add_node(gs.Node('29', 80))
    new_graph.add_node(gs.Node('30', 100))
    new_graph.add_node(gs.Node('31', 70))
    new_graph.add_node(gs.Node('32', 81))
    new_graph.add_node(gs.Node('33', 75))
    new_graph.add_node(gs.Node('34', 79))
    new_graph.add_node(gs.Node('35', 78))
    new_graph.add_node(gs.Node('36', 74))
    new_graph.add_node(gs.Node('37', 78))
    new_graph.add_node(gs.Node('38', 70))
    new_graph.add_node(gs.Node('39', 73))
    new_graph.add_node(gs.Node('40', 76))
    new_graph.add_node(gs.Node('41', 74))
    new_graph.add_node(gs.Node('42', 70))
    new_graph.add_node(gs.Node('43', 65))
    new_graph.add_node(gs.Node('44', 62))
    new_graph.add_node(gs.Node('45', 58))
    new_graph.add_node(gs.Node('46', 57))
    new_graph.add_node(gs.Node('47', 58))
    new_graph.add_node(gs.Node('48', 40))
    new_graph.add_node(gs.Node('49', 50))
    new_graph.add_node(gs.Node('50', 38))
    new_graph.add_node(gs.Node('51', 38))
    new_graph.add_node(gs.Node('52', 40))
    new_graph.add_node(gs.Node('53', 20))
    new_graph.add_node(gs.Node('54', 17))
    new_graph.add_node(gs.Node('55', 0))
    new_graph.add_node(gs.Node('56', 39))
    new_graph.add_node(gs.Node('57', 42))
    new_graph.add_node(gs.Node('58', 46))
    new_graph.add_node(gs.Node('59', 52))

    # Third parameter - cost ( in meters ).
    new_graph.create_link('1', '6', 50, True, gs.Link.transition)
    new_graph.create_link('1', '2', 44, True, gs.Link.standard)
    new_graph.create_link('6', '5', 39, True, gs.Link.roundabout)
    new_graph.create_link('2', '3', 31, True, gs.Link.transition)
    new_graph.create_link('3', '4', 41, True, gs.Link.roundabout)
    new_graph.create_link('4', '5', 32, True, gs.Link.roundabout)
    new_graph.create_link('6', '7', 52, True, gs.Link.standard)
    new_graph.create_link('7', '8', 31, True, gs.Link.standard)
    new_graph.create_link('7', '11', 32, True, gs.Link.transition)
    new_graph.create_link('8', '9', 30, True, gs.Link.standard)
    new_graph.create_link('9', '10', 28, True, gs.Link.standard)
    new_graph.create_link('11', '14', 41, True, gs.Link.roundabout)
    new_graph.create_link('11', '12', 41, True, gs.Link.roundabout)
    new_graph.create_link('12', '13', 41, True, gs.Link.roundabout)
    new_graph.create_link('12', '49', 35, True, gs.Link.standard)
    new_graph.create_link('49', '48', 35, True, gs.Link.standard)
    new_graph.create_link('48', '47', 49, True, gs.Link.standard)
    new_graph.create_link('48', '50', 40, True, gs.Link.standard)
    new_graph.create_link('47', '46', 40, True, gs.Link.transition)
    new_graph.create_link('46', '50', 49, True, gs.Link.roundabout)
    new_graph.create_link('50', '51', 28, True, gs.Link.standard)
    new_graph.create_link('46', '45', 28, True, gs.Link.standard)
    new_graph.create_link('45', '51', 49, True, gs.Link.roundabout)
    new_graph.create_link('51', '52', 30, True, gs.Link.standard)
    new_graph.create_link('45', '44', 58, True, gs.Link.standard)
    new_graph.create_link('52', '43', 40, True, gs.Link.standard)
    new_graph.create_link('43', '44', 49, True, gs.Link.standard)
    new_graph.create_link('44', '42', 30, True, gs.Link.transition)
    new_graph.create_link('42', '41', 26, True, gs.Link.roundabout)
    new_graph.create_link('41', '40', 42, True, gs.Link.roundabout)
    new_graph.create_link('40', '39', 44, True, gs.Link.roundabout)
    new_graph.create_link('39', '43', 47, True, gs.Link.transition)
    new_graph.create_link('39', '38', 48, True, gs.Link.standard)
    new_graph.create_link('38', '59', 24, True, gs.Link.standard)
    new_graph.create_link('38', '36', 24, True, gs.Link.standard)
    new_graph.create_link('36', '37', 26, True, gs.Link.roundabout)
    new_graph.create_link('36', '35', 26, True, gs.Link.roundabout)
    new_graph.create_link('35', '34', 24, True, gs.Link.standard)
    new_graph.create_link('34', '33', 48, True, gs.Link.standard)
    new_graph.create_link('33', '32', 27, True, gs.Link.standard)
    new_graph.create_link('32', '29', 30, True, gs.Link.standard)
    new_graph.create_link('29', '30', 34, True, gs.Link.standard)
    new_graph.create_link('29', '28', 20, True, gs.Link.transition)
    new_graph.create_link('32', '31', 34, True, gs.Link.standard)
    new_graph.create_link('31', '27', 15, True, gs.Link.transition)
    new_graph.create_link('27', '28', 26, True, gs.Link.roundabout)
    new_graph.create_link('27', '26', 26, True, gs.Link.roundabout)
    new_graph.create_link('26', '25', 29, True, gs.Link.standard)
    new_graph.create_link('25', '22', 28, True, gs.Link.standard)
    new_graph.create_link('22', '21', 16, True, gs.Link.standard)
    new_graph.create_link('21', '20', 60, True, gs.Link.roundabout)
    new_graph.create_link('20', '19', 19, True, gs.Link.transition)
    new_graph.create_link('19', '18', 30, True, gs.Link.roundabout)
    new_graph.create_link('18', '17', 32, True, gs.Link.standard)
    new_graph.create_link('17', '20', 30, True, gs.Link.standard)
    new_graph.create_link('17', '16', 27, True, gs.Link.standard)
    new_graph.create_link('16', '15', 35, True, gs.Link.standard)
    new_graph.create_link('15', '23', 30, True, gs.Link.standard)
    new_graph.create_link('23', '24', 29, True, gs.Link.standard)
    new_graph.create_link('24', '25', 57, True, gs.Link.standard)
    new_graph.create_link('22', '23', 57, True, gs.Link.standard)
    new_graph.create_link('15', '14', 23, True, gs.Link.standard)
    new_graph.create_link('14', '13', 26, True, gs.Link.roundabout)
    new_graph.create_link('13', '55', 30, True, gs.Link.standard)
    new_graph.create_link('55', '54', 28, True, gs.Link.transition)
    new_graph.create_link('24', '54', 28, True, gs.Link.transition)
    new_graph.create_link('54', '56', 27, True, gs.Link.roundabout)
    new_graph.create_link('54', '53', 27, True, gs.Link.roundabout)
    new_graph.create_link('56', '57', 27, True, gs.Link.roundabout)
    new_graph.create_link('53', '57', 27, True, gs.Link.roundabout)
    new_graph.create_link('53', '52', 55, True, gs.Link.standard)
    new_graph.create_link('57', '58', 27, True, gs.Link.standard)
    new_graph.create_link('58', '59', 28, True, gs.Link.standard)
